a/C:\temp\script.js → b/C:\temp\script.js
@@ -1,102 +1,108 @@
 // I Ching Number Divination - JavaScript
+// 先天八卦：乾一、兌二、離三、震四、巽五、坎六、艮七、坤八
 
-// 八卦對應表
 const eightTrigrams = {
-    1: { name: "Qian (Creativity)", symbol: "☰", chinese: "乾" },
-    2: { name: "Dui (Joy)", symbol: "☱", chinese: "兌" },
-    3: { name: "Li (Clarity)", symbol: "☲", chinese: "離" },
-    4: { name: "Zhen (Thunder)", symbol: "☳", chinese: "震" },
-    5: { name: "Xun (Gentle)", symbol: "☴", chinese: "巽" },
-    6: { name: "Kan (Depth)", symbol: "☵", chinese: "坎" },
-    7: { name: "Gen (Mountain)", symbol: "☶", chinese: "艮" },
-    8: { name: "Kun (Earth)", symbol: "☷", chinese: "坤" }
+    1: { name: "Qian", symbol: "☰", chinese: "乾", english: "Creativity" },
+    2: { name: "Dui", symbol: "☱", chinese: "兌", english: "Joy" },
+    3: { name: "Li", symbol: "☲", chinese: "離", english: "Clarity" },
+    4: { name: "Zhen", symbol: "☳", chinese: "震", english: "Thunder" },
+    5: { name: "Xun", symbol: "☴", chinese: "巽", english: "Gentle" },
+    6: { name: "Kan", symbol: "☵", chinese: "坎", english: "Depth" },
+    7: { name: "Gen", symbol: "☶", chinese: "艮", english: "Mountain" },
+    8: { name: "Kun", symbol: "☷", chinese: "坤", english: "Earth" }
 };
 
-function getExtendedHexagram(num) {
-    const baseHexagrams = {
-        1: { name: "Hexagram 1 - Creative Heaven", chinese: "乾為天", trigram: "☰☰", meaning: "Pure Yang energy, creativity, and new beginnings. The creative force that initiates all things.", guidance: "This is a time of powerful new beginnings. Trust your creative energy and take initiative." },
-        2: { name: "Hexagram 2 - Receptive Earth", chinese: "坤為地", trigram: "☷☷", meaning: "Pure Yin energy, receptivity, and nurturing. The earth that supports all life.", guidance: "Be patient and receptive. Allow things to develop naturally." },
-        3: { name: "Hexagram 3 - Difficulty at the Beginning", chinese: "屯為水", trigram: "☵☰", meaning: "Difficulty in starting new ventures. Like a seed pushing through earth.", guidance: "Obstacles are temporary. Keep pushing forward." },
-        4: { name: "Hexagram 4 - Youthful Folly", chinese: "蒙為山", trigram: "☶☵", meaning: "Need for education and guidance. Youth needs instruction.", guidance: "Seek knowledge and find a mentor." },
-        5: { name: "Hexagram 5 - Waiting", chinese: "需為水", trigram: "☰☵", meaning: "Time of waiting and preparation. Like rain that must fall before growth.", guidance: "Patience is needed. Prepare while you wait." },
-        6: { name: "Hexagram 6 - Conflict", chinese: "讼為天", trigram: "☵☰", meaning: "Conflict and dispute. Testing of will.", guidance: "Seek harmony. Avoid unnecessary conflict." },
-        7: { name: "Hexagram 7 - The Army", chinese: "師為地", trigram: "☷☵", meaning: "The army represents organization and discipline.", guidance: "You need structure and organization." },
-        8: { name: "Hexagram 8 - Holding Together", chinese: "比為水", trigram: "☵☷", meaning: "Unity and closeness. Support from others.", guidance: "Work with others. Unity brings strength." },
-        9: { name: "Hexagram 9 - The Taming Power", chinese: "小畜天", trigram: "☴☰", meaning: "Small taming and accumulation. Building slowly.", guidance: "Progress is slow but steady. Keep building." },
-        10: { name: "Hexagram 10 - Treading Carefully", chinese: "履為天", trigram: "☰☱", meaning: "Careful conduct in difficult situations.", guidance: "Proceed with caution and integrity." },
-        11: { name: "Hexagram 11 - Peace", chinese: "泰為地", trigram: "☰☷", meaning: "Peace and harmony. A time of prosperity.", guidance: "Enjoy this time of harmony and prosperity." },
-        12: { name: "Hexagram 12 - Stagnation", chinese: "否為天", trigram: "☷☰", meaning: "Stagnation and blockage. Difficult times.", guidance: "This too shall pass. Wait for the turn." },
-        13: { name: "Hexagram 13 - Fellowship", chinese: "同人天", trigram: "☰☲", meaning: "Union and partnership. Working together.", guidance: "Seek partnership and collaboration." },
-        14: { name: "Hexagram 14 - Great Possession", chinese: "大有火", trigram: "☲☰", meaning: "Great abundance and success.", guidance: "You are entering a time of abundance." },
-        15: { name: "Hexagram 15 - Modesty", chinese: "謙為山", trigram: "☶☷", meaning: "Humility brings advancement.", guidance: "Stay humble. Your modesty will be rewarded." },
-        16: { name: "Hexagram 16 - Enthusiasm", chinese: "豫為雷", trigram: "☳☷", meaning: "Joy and excitement. New opportunities.", guidance: "Seize this opportunity with enthusiasm." },
-        17: { name: "Hexagram 17 - Following", chinese: "随為澤", trigram: "☱☳", meaning: "Following and adapting. Finding guidance.", guidance: "Follow wise counsel and adapt." },
-        18: { name: "Hexagram 18 - Work on what is Decayed", chinese: "蠱為山", trigram: "☶☴", meaning: "Repairing and restoring. Fixing problems.", guidance: "Time to address and fix problems." },
-        19: { name: "Hexagram 19 - Approach", chinese: "臨為地", trigram: "☷☰", meaning: "Approaching success. Drawing near to goals.", guidance: "You are approaching your goals. Stay the course." },
-        20: { name: "Hexagram 20 - Contemplation", chinese: "觀為風", trigram: "☴☷", meaning: "Observation and reflection. Learning from above.", guidance: "Take time to observe and reflect." },
-        21: { name: "Hexagram 21 - Biting Through", chinese: "噬嗑為雷", trigram: "☳☲", meaning: "Biting through obstacles. Taking action.", guidance: "Take decisive action on problems." },
-        22: { name: "Hexagram 22 - Grace", chinese: "賁為山", trigram: "☶☲", meaning: "Grace and adornment. External beauty.", guidance: "Focus on presentation and appearance." },
-        23: { name: "Hexagram 23 - Splitting Apart", chinese: "剝為山", trigram: "☶☷", meaning: "Breaking down. A time of decline.", guidance: "This is a time of withdrawal and healing." },
-        24: { name: "Hexagram 24 - Return", chinese: "復為雷", trigram: "☳☷", meaning: "Return and renewal. The turning point.", guidance: "A new cycle is beginning. Return to your path." },
-        25: { name: "Hexagram 25 - Innocence", chinese: "無妄天", trigram: "☰☳", meaning: "Natural innocence. Being without pretension.", guidance: "Be honest and straightforward." },
-        26: { name: "Hexagram 26 - Great Taming", chinese: "大畜山", trigram: "☶☰", meaning: "Great restraint and accumulation. Building power.", guidance: "Build your strength through restraint." },
-        27: { name: "Hexagram 27 - The Corners of the Mouth", chinese: "頤為山", trigram: "☶☳", meaning: "Nourishment and sustenance. Feeding properly.", guidance: "Take care of your basic needs." },
-        28: { name: "Hexagram 28 - Great Excess", chinese: "大過澤", trigram: "☱☴", meaning: "Great exceeding. Going beyond limits.", guidance: "Be careful of excess. Balance is key." },
-        29: { name: "Hexagram 29 - The Abyss", chinese: "坎為水", trigram: "☵☵", meaning: "The dangerous pit. Deep waters.", guidance: "Be careful. Danger is near." },
-        30: { name: "Hexagram 30 - The Clinging Fire", chinese: "離為火", trigram: "☲☲", meaning: "Clinging fire. Light and clarity.", guidance: "Seek clarity and illumination." },
-        31: { name: "Hexagram 31 - Influence", chinese: "咸為澤", trigram: "☱☶", meaning: "Influence and attraction. Mutual feeling.", guidance: "Attraction and connection are important." },
-        32: { name: "Hexagram 32 - Duration", chinese: "恆為雷", trigram: "☳☴", meaning: "Duration and constancy. Lasting relationships.", guidance: "Stay constant. Duration brings success." },
-        33: { name: "Hexagram 33 - Retreat", chinese: "遯為天", trigram: "☰☶", meaning: "Strategic retreat. Withdrawing wisely.", guidance: "Sometimes retreat is the best strategy." },
-        34: { name: "Hexagram 34 - The Power of the Great", chinese: "大壯雷", trigram: "☳☰", meaning: "Great power and strength. Building force.", guidance: "Your power is growing. Use it wisely." },
-        35: { name: "Hexagram 35 - Progress", chinese: "晉為火", trigram: "☲☷", meaning: "Progress and advancement. Gaining recognition.", guidance: "You are progressing well. Continue forward." },
-        36: { name: "Hexagram 36 - Darkness of the Sun", chinese: "明夷地", trigram: "☷☲", meaning: "Hidden brightness. Light in darkness.", guidance: "Stay strong even in difficult times." },
-        37: { name: "Hexagram 37 - The Family", chinese: "家人風", trigram: "☴☲", meaning: "Family and household. Home life.", guidance: "Focus on family and home matters." },
-        38: { name: "Hexagram 38 - Opposition", chinese: "睽為澤", trigram: "☱☲", meaning: "Opposition and contrast. Differences.", guidance: "Even opposites can work together." },
-        39: { name: "Hexagram 39 - Obstruction", chinese: "蹇為水", trigram: "☵☶", meaning: "Difficulty and blockage. Moving forward is hard.", guidance: "This is a time of difficulty. Be patient." },
-        40: { name: "Hexagram 40 - Deliverance", chinese: "解為雷", trigram: "☳☵", meaning: "Release and deliverance. Freedom from trouble.", guidance: "Your difficulties are ending. Freedom is coming." },
-        41: { name: "Hexagram 41 - Decrease", chinese: "損為山", trigram: "☶☱", meaning: "Decrease and sacrifice. Giving up for gain.", guidance: "Sometimes you must decrease to increase." },
-        42: { name: "Hexagram 42 - Increase", chinese: "益為雷", trigram: "☳☴", meaning: "Increase and growth. Adding to yourself.", guidance: "You are growing and increasing." },
-        43: { name: "Hexagram 43 - Resolution", chinese: "夬為澤", trigram: "☱☰", meaning: "Resolution and decision. Breaking through.", guidance: "Time to make a decisive move." },
-        44: { name: "Hexagram 44 - Meeting", chinese: "姤為風", trigram: "☴☰", meaning: "Meeting and coming together. Unexpected meeting.", guidance: "An unexpected meeting or opportunity approaches." },
-        45: { name: "Hexagram 45 - Gathering Together", chinese: "萃為澤", trigram: "☱☷", meaning: "Gathering and union. People coming together.", guidance: "Unity brings strength. Work together." },
-        46: { name: "Hexagram 46 - Pushing Upward", chinese: "升為地", trigram: "☷☳", meaning: "Rising upward. Gradual advancement.", guidance: "You are rising. Keep pushing upward." },
-        47: { name: "Hexagram 47 - Oppression", chinese: "困為澤", trigram: "☱☵", meaning: "Exhaustion and oppression. Being trapped.", guidance: "You feel trapped but stay strong." },
-        48: { name: "Hexagram 48 - The Well", chinese: "井為水", trigram: "☵☴", meaning: "The well as a resource. Sustaining others.", guidance: "You are a source of sustenance for others." },
-        49: { name: "Hexagram 49 - Revolution", chinese: "革為澤", trigram: "☱☲", meaning: "Revolution and change. Transformation.", guidance: "Major changes are happening." },
-        50: { name: "Hexagram 50 - The Cauldron", chinese: "鼎為風", trigram: "☴☲", meaning: "The cauldron as transformation. New values.", guidance: "Transformation is occurring." },
-        51: { name: "Hexagram 51 - Thunder and Lightning", chinese: "震為雷", trigram: "☳☳", meaning: "Thunder and shock. Sudden events.", guidance: "Sudden events are coming. Stay prepared." },
-        52: { name: "Hexagram 52 - Keeping Still", chinese: "艮為山", trigram: "☶☶", meaning: "Stillness and stopping. Meditation.", guidance: "Be still. Focus on inner peace." },
-        53: { name: "Hexagram 53 - Gradual Progress", chinese: "漸為風", trigram: "☴☶", meaning: "Gradual development. Step by step.", guidance: "Progress slowly but steadily." },
… omitted 161 diff line(s) across 1 additional file(s)/section(s)
